"""Initial Migration

Revision ID: 7ec157a2182d
Revises: 3098c2b195d5
Create Date: 2020-09-22 22:20:40.074950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec157a2182d'
down_revision = '3098c2b195d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_writer_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'writer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('writer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_writer_fkey', 'pitches', 'users', ['writer'], ['id'])
    # ### end Alembic commands ###
